services:
  pizza-api:
    container_name: pizza-api
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /venv
    command: ["uv", "run", "uvicorn", "app.main:create_app", "--factory", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: techtask-db
    image: postgres:15-alpine
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
